version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Asia/Tokyo

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Asia/Tokyo

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Asia/Tokyo
